name: OpenEffect
main: net.example.openeffect.OpenEffectPlugin
version: 1.0.1
api-version: '1.20'
commands:
  open:
    description: OpenEffect toggle
    usage: /open effect <on|off>
permissions:
  openeffect.admin:
    default: op
  openeffect.toggle:
    default: false
